### 1. Write Python Programs to use various operators in Python



In [16]:
a  =  10
b  =  3
add=a+b
sub=a-b
mul=a*b
power=a**b
div=a/b
div1=a//b
mode=a%b
print(add,sub,mul,power,div,div1,mode)
if(a==b):
    print("both are equal")
elif(a!=b):
    print("both are not equal")
elif(a>b):
    print("a is greater")
elif(a>=b):
    print("a is greater or equal")
elif(a<=b):
    print("less than or equal")
elif(a<b):
    print("b is greater")
elif(a&b==0):
    print("both are zero")
print("this are the Operators")
                            

13 7 30 1000 3.3333333333333335 3 1
both are not equal
this are the Operators


### 2. Create list of elements and slice and dice it



In [ ]:
### 2. Create list of elements and slice and dice it


In [18]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)
areas[1:3]

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


[11.25, 'kitchen']

### 3. Using while loop accept numbers until sum of numbers is less than 100



In [24]:
num=0
sum=0
while(num<100):
    sum=sum+num
    num=num+1
    if(sum<=100):
        print(sum)



0
1
3
6
10
15
21
28
36
45
55
66
78
91


### 4. Write a python program Read & write Excel files 



In [ ]:
import pandas as pd
data=pd.read_excel("new_file.xlsx",'r')
data=pd.read_excel("new_file.xlsx",'w')

### 5. Write a python program to scrape reviews from a commercial web site



In [ ]:
import requests
print(requests.get('https://w3resource.com'))
print(requests.get('https://wayback.com'))

### 6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy



In [63]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array



In [68]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


### 8. "Write a Python program to create a null vector of size 10 and update sixth value to 11.



In [69]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
